#!/bin/bash
# SM8550 MSPv2 - tools/capture_state.sh
# Capture the current system state before applying a profile.
# Restore with restore.sh which sources this state file.
#
# Usage:
#   source tools/capture_state.sh    # from within runtime/*.sh
#   ./tools/capture_state.sh         # standalone
#
# Design: Each profile calls capture_state exactly once BEFORE making changes.
# The capture_state function will:
#   - If STATE_FILE exists and is fresh (owned by same PID? we use timestamp), do NOT overwrite.
#   - Else capture clean state.
#   - Export STATE_OWNER and STATE_TIMESTAMP for restore.sh to verify.
#
# restore.sh will:
#   - If STATE_FILE exists and STATE_OWNER matches the profile that created it, restore.
#   - Else if STATE_FILE exists but OWNER differs, refuse to restore (to avoid clobbering).
#   - If no STATE_FILE, apply safe defaults (separate mode).

set -euo pipefail

# Files
STATE_FILE="${MSPV2_STATE_FILE:-/tmp/mspv2_state.sh}"
STATE_OWNER_FILE="${MSPV2_STATE_OWNER_FILE:-/tmp/mspv2_state.owner}"
STATE_TIMESTAMP_FILE="${MSPV2_STATE_TIMESTAMP_FILE:-/tmp/mspv2_state.timestamp}"

# Helper: check if state file is fresh (less than 5 minutes old)
state_is_fresh() {
    [ -f "$STATE_TIMESTAMP_FILE" ] || return 1
    local now then_val
    now=$(date +%s)
    then_val=$(cat "$STATE_TIMESTAMP_FILE")
    local age=$((now - then_val))
    [ "$age" -lt 300 ]  # 5 minutes
}

capture_state() {
    # If we already have a fresh state file, do NOT overwrite.
    if state_is_fresh && [ -f "$STATE_OWNER_FILE" ]; then
        # Already captured, just return.
        return 0
    fi

    {
        echo "# MSPv2 state capture - $(date)"
        echo "# Generated by sm8550_mspv2 capture_state.sh"
        echo ""
        echo "# Per-cgroup UCLAMP values"
    } >> "$STATE_FILE"
    local uclamp_count=0
    for path in /dev/cpuctl/*/uclamp.{min,max}; do
        [ -r "$path" ] || continue
        local val
        val=$(cat "$path" 2>/dev/null || echo "")
        [ -n "$val" ] || continue
        echo "UCLAMP_PATH[$uclamp_count]=\"$path\"" >> "$STATE_FILE"
        echo "UCLAMP_VAL[$uclamp_count]=\"$val\"" >> "$STATE_FILE"
        uclamp_count=$((uclamp_count + 1))
    done

    # ---- CPUfreq -----------------------------------------------------------
    echo "" >> "$STATE_FILE"
    echo "# CPUfreq scaling_min/max and governor" >> "$STATE_FILE"
    local cpufq_count=0
    for policy in /sys/devices/system/cpu/cpufreq/policy*; do
        [ -d "$policy" ] || continue
        for attr in scaling_min_freq scaling_max_freq scaling_governor \
                    schedutil/up_rate_limit_us schedutil/down_rate_limit_us; do
            [ -r "$policy/$attr" ] || continue
            local val
            val=$(cat "$policy/$attr" 2>/dev/null || echo "")
            [ -n "$val" ] || continue
            echo "CPUFQ_PATH[$cpufq_count]=\"$policy/$attr\"" >> "$STATE_FILE"
            echo "CPUFQ_VAL[$cpufq_count]=\"$val\"" >> "$STATE_FILE"
            cpufq_count=$((cpufq_count + 1))
        done
    done

    # ---- Devfreq -----------------------------------------------------------
    echo "" >> "$STATE_FILE"
    echo "# Devfreq min_freq, max_freq, governor" >> "$STATE_FILE"
    local devfq_count=0
    for devfreq in /sys/class/devfreq/*; do
        [ -d "$devfreq" ] || continue
        for attr in min_freq max_freq governor; do
            [ -r "$devfreq/$attr" ] || continue
            local val
            val=$(cat "$devfreq/$attr" 2>/dev/null || echo "")
            [ -n "$val" ] || continue
            echo "DEVFQ_PATH[$devfq_count]=\"$devfreq/$attr\"" >> "$STATE_FILE"
            echo "DEVFQ_VAL[$devfq_count]=\"$val\"" >> "$STATE_FILE"
            devfq_count=$((devfq_count + 1))
        done
    done

    # ---- cpuidle -----------------------------------------------------------
    echo "" >> "$STATE_FILE"
    echo "# CPU idle state disable values" >> "$STATE_FILE"
    local idle_count=0
    for state in /sys/devices/system/cpu/cpu*/cpuidle/state*; do
        [ -r "$state/disable" ] || continue
        local val
        val=$(cat "$state/disable" 2>/dev/null || echo "")
        [ -n "$val" ] || continue
        echo "IDLE_PATH[$idle_count]=\"$state/disable\"" >> "$STATE_FILE"
        echo "IDLE_VAL[$idle_count]=\"$val\"" >> "$STATE_FILE"
        idle_count=$((idle_count + 1))
    done

    # ---- Block I/O ---------------------------------------------------------
    echo "" >> "$STATE_FILE"
    echo "# Block device queue settings" >> "$STATE_FILE"
    local io_count=0
    for queue in /sys/block/*/queue; do
        [ -d "$queue" ] || continue
        for attr in scheduler read_ahead_kb nr_requests nomerges rq_affinity; do
            [ -r "$queue/$attr" ] || continue
            local val
            val=$(cat "$queue/$attr" 2>/dev/null || echo "")
            [ -n "$val" ] || continue
            echo "IOQ_PATH[$io_count]=\"$queue/$attr\"" >> "$STATE_FILE"
            echo "IOQ_VAL[$io_count]=\"$val\"" >> "$STATE_FILE"
            io_count=$((io_count + 1))
        done
    done

    # ---- IRQ affinity (optional, only if MSPv2 changed it) -----------------
    # We do not capture IRQ affinity by default because it's expensive and
    # restore.sh will only restore IRQs that MSPv2 actually touched.
    # Instead, restore.sh will re-run detect_irqs.sh and apply the saved masks.
    # So we capture nothing here for IRQ.

    echo "" >> "$STATE_FILE"
    echo "# State capture complete." >> "$STATE_FILE"

    # Record owner and timestamp
    echo "$$" > "$STATE_OWNER_FILE"
    date +%s > "$STATE_TIMESTAMP_FILE"
}

# If sourced, just define the function; if executed, run capture.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    capture_state
    echo "State captured to $STATE_FILE"
fi