#!/bin/bash
# SM8550 MSPv2 - tools/capture_state.sh
# Capture the current system state before applying a profile.
# Restore with restore.sh which sources this state file.
#
# Usage:
#   source tools/capture_state.sh    # from within runtime/*.sh
#   ./tools/capture_state.sh         # standalone

set -euo pipefall

STATE_FILE="${MSPV2_STATE_FILE:-/tmp/mspv2_state.sh}"

capture_state() {
    echo "# MSPv2 state capture - $(date)" > "$STATE_FILE"
    echo "# Generated by sm8550_mspv2 capture_state.sh" >> "$STATE_FILE"

    # ---- UCLAMP -----------------------------------------------------------
    echo "" >> "$STATE_FILE"
    echo "# Per-cgroup UCLAMP values" >> "$STATE_FILE"
    local uclamp_count=0
    for path in /dev/cpuctl/*/uclamp.{min,max}; do
        [ -r "$path" ] || continue
        local val
        val=$(cat "$path" 2>/dev/null || echo "")
        [ -n "$val" ] || continue
        echo "UCLAMP_PATH[$uclamp_count]=\"$path\"" >> "$STATE_FILE"
        echo "UCLAMP_VAL[$uclamp_count]=\"$val\"" >> "$STATE_FILE"
        uclamp_count=$((uclamp_count + 1))
    done

    # ---- CPUfreq -----------------------------------------------------------
    echo "" >> "$STATE_FILE"
    echo "# CPUfreq scaling_min/max and governor" >> "$STATE_FILE"
    local cpufq_count=0
    for policy in /sys/devices/system/cpu/cpufreq/policy*; do
        [ -d "$policy" ] || continue
        for attr in scaling_min_freq scaling_max_freq scaling_governor \
                    schedutil/up_rate_limit_us schedutil/down_rate_limit_us; do
            [ -r "$policy/$attr" ] || continue
            local val
            val=$(cat "$policy/$attr" 2>/dev/null || echo "")
            [ -n "$val" ] || continue
            echo "CPUFQ_PATH[$cpufq_count]=\"$policy/$attr\"" >> "$STATE_FILE"
            echo "CPUFQ_VAL[$cpufq_count]=\"$val\"" >> "$STATE_FILE"
            cpufq_count=$((cpufq_count + 1))
        done
    done

    # ---- Devfreq -----------------------------------------------------------
    echo "" >> "$STATE_FILE"
    echo "# Devfreq min_freq, max_freq, governor" >> "$STATE_FILE"
    local devfq_count=0
    for devfreq in /sys/class/devfreq/*; do
        [ -d "$devfreq" ] || continue
        for attr in min_freq max_freq governor; do
            [ -r "$devfreq/$attr" ] || continue
            local val
            val=$(cat "$devfreq/$attr" 2>/dev/null || echo "")
            [ -n "$val" ] || continue
            echo "DEVFQ_PATH[$devfq_count]=\"$devfreq/$attr\"" >> "$STATE_FILE"
            echo "DEVFQ_VAL[$devfq_count]=\"$val\"" >> "$STATE_FILE"
            devfq_count=$((devfq_count + 1))
        done
    done

    # ---- cpuidle -----------------------------------------------------------
    echo "" >> "$STATE_FILE"
    echo "# CPU idle state disable values" >> "$STATE_FILE"
    local idle_count=0
    for state in /sys/devices/system/cpu/cpu*/cpuidle/state*; do
        [ -r "$state/disable" ] || continue
        local val
        val=$(cat "$state/disable" 2>/dev/null || echo "")
        [ -n "$val" ] || continue
        echo "IDLE_PATH[$idle_count]=\"$state/disable\"" >> "$STATE_FILE"
        echo "IDLE_VAL[$idle_count]=\"$val\"" >> "$STATE_FILE"
        idle_count=$((idle_count + 1))
    done

    # ---- Block I/O ---------------------------------------------------------
    echo "" >> "$STATE_FILE"
    echo "# Block device queue settings" >> "$STATE_FILE"
    local io_count=0
    for queue in /sys/block/*/queue; do
        [ -d "$queue" ] || continue
        for attr in scheduler read_ahead_kb nr_requests nomerges; do
            [ -r "$queue/$attr" ] || continue
            local val
            val=$(cat "$queue/$attr" 2>/dev/null || echo "")
            [ -n "$val" ] || continue
            echo "IOQ_PATH[$io_count]=\"$queue/$attr\"" >> "$STATE_FILE"
            echo "IOQ_VAL[$io_count]=\"$val\"" >> "$STATE_FILE"
            io_count=$((io_count + 1))
        done
    done

    echo "" >> "$STATE_FILE"
    echo "# State capture complete." >> "$STATE_FILE"
}

# Auto-run if executed directly (not sourced)
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    capture_state
    echo "State captured to $STATE_FILE"
else
    capture_state
fi
